# Generated by Django 5.2.4 on 2025-10-29 13:32

import club.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=24)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('is_partner', models.BooleanField(default=False, help_text='OTP for partner registration')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_for_referrer', models.IntegerField(default=50, help_text='Points awarded to referrer when friend joins')),
                ('points_for_referee', models.IntegerField(default=20, help_text='Points awarded to new user who was referred')),
                ('max_referrals_per_user', models.IntegerField(blank=True, help_text='Maximum referrals per user (null = unlimited)', null=True)),
                ('referral_enabled', models.BooleanField(default=True, help_text='Enable/disable referral system')),
            ],
            options={
                'verbose_name': 'Referral Settings',
                'verbose_name_plural': 'Referral Settings',
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text="Partner's phone number", max_length=24, unique=True)),
                ('name', models.CharField(help_text='Partnership/Business name', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Unique partnership code', max_length=8, unique=True)),
                ('partner_type', models.CharField(choices=[('influencer', 'Influencer'), ('shop', 'Shop/Retailer')], default='influencer', help_text='Type of partner', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('county', models.CharField(blank=True, help_text='County (for shops)', max_length=50)),
                ('location_details', models.TextField(blank=True, help_text='Detailed location/address')),
                ('points_per_scan', models.IntegerField(default=5, help_text='Points partner earns per scan by referred users')),
                ('total_points_earned', models.IntegerField(default=0, help_text='Total points earned from referrals')),
                ('active', models.BooleanField(default=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pending_payout', models.DecimalField(decimal_places=2, default=0.0, help_text='Monetary value pending payout', max_digits=10)),
                ('total_payout', models.DecimalField(decimal_places=2, default=0.0, help_text='Total paid out to partner', max_digits=10)),
                ('user', models.OneToOneField(blank=True, help_text='User account for partner login', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partnership',
                'verbose_name_plural': 'Partnerships',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=24, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('second_name', models.CharField(blank=True, max_length=50)),
                ('county', models.CharField(blank=True, choices=[('mombasa', 'Mombasa'), ('kwale', 'Kwale'), ('kilifi', 'Kilifi'), ('tana_river', 'Tana River'), ('lamu', 'Lamu'), ('taita_taveta', 'Taita Taveta'), ('garissa', 'Garissa'), ('wajir', 'Wajir'), ('mandera', 'Mandera'), ('marsabit', 'Marsabit'), ('isiolo', 'Isiolo'), ('meru', 'Meru'), ('tharaka_nithi', 'Tharaka Nithi'), ('embu', 'Embu'), ('kitui', 'Kitui'), ('machakos', 'Machakos'), ('makueni', 'Makueni'), ('nyandarua', 'Nyandarua'), ('nyeri', 'Nyeri'), ('kirinyaga', 'Kirinyaga'), ('muranga', "Murang'a"), ('kiambu', 'Kiambu'), ('turkana', 'Turkana'), ('west_pokot', 'West Pokot'), ('samburu', 'Samburu'), ('trans_nzoia', 'Trans Nzoia'), ('uasin_gishu', 'Uasin Gishu'), ('elgeyo_marakwet', 'Elgeyo Marakwet'), ('nandi', 'Nandi'), ('baringo', 'Baringo'), ('laikipia', 'Laikipia'), ('nakuru', 'Nakuru'), ('narok', 'Narok'), ('kajiado', 'Kajiado'), ('kericho', 'Kericho'), ('bomet', 'Bomet'), ('kakamega', 'Kakamega'), ('vihiga', 'Vihiga'), ('bungoma', 'Bungoma'), ('busia', 'Busia'), ('siaya', 'Siaya'), ('kisumu', 'Kisumu'), ('homa_bay', 'Homa Bay'), ('migori', 'Migori'), ('kisii', 'Kisii'), ('nyamira', 'Nyamira'), ('nairobi', 'Nairobi')], max_length=50)),
                ('buyer_type', models.CharField(blank=True, choices=[('home', 'Home Use'), ('business', 'Business Use')], max_length=10)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('referral_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('referral_points_earned', models.IntegerField(default=0)),
                ('partnership', models.ForeignKey(blank=True, help_text='Partnership that referred this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_profiles', to='club.partnership')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='club.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=club.models.generate_pack_code, max_length=128, unique=True)),
                ('sku', models.CharField(default='Lea-1kg', max_length=64)),
                ('points', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded_to_referrer', models.IntegerField()),
                ('points_awarded_to_referred', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_event', to='club.profile')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_events', to='club.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost_points', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('available_at_shops', models.BooleanField(default=False, help_text='Can be redeemed at partner shops')),
                ('partner_shops', models.ManyToManyField(blank=True, help_text='Shops where this reward can be redeemed', limit_choices_to={'partner_type': 'shop'}, related_name='available_rewards', to='club.partnership')),
            ],
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved by Shop'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('fulfilled', models.BooleanField(default=False)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('redemption_code', models.CharField(blank=True, help_text='Code for shop to verify redemption', max_length=8, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.profile')),
                ('redeemed_at_shop', models.ForeignKey(blank=True, help_text='Shop where reward was redeemed', limit_choices_to={'partner_type': 'shop'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.partnership')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.reward')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.IntegerField()),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('partnership_points_awarded', models.BooleanField(default=False)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.packcode')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PartnershipEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.IntegerField(help_text='Points earned by partner from this scan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='club.partnership')),
                ('profile', models.ForeignKey(help_text='User who made the scan', on_delete=django.db.models.deletion.CASCADE, to='club.profile')),
                ('scan', models.ForeignKey(help_text='The scan that generated earnings', on_delete=django.db.models.deletion.CASCADE, to='club.scan')),
            ],
            options={
                'verbose_name': 'Partnership Earning',
                'verbose_name_plural': 'Partnership Earnings',
                'ordering': ['-created_at'],
            },
        ),
    ]

