# Generated by Django 5.2.4 on 2025-11-08 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransferSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_enabled', models.BooleanField(default=True, help_text='Enable/disable point transfers')),
                ('min_transfer_amount', models.IntegerField(default=10, help_text='Minimum points that can be transferred')),
                ('max_transfer_amount', models.IntegerField(default=500, help_text='Maximum points per transfer')),
                ('daily_transfer_limit', models.IntegerField(default=1000, help_text='Maximum points user can transfer per day')),
                ('transfer_fee_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee percentage (0-100). E.g., 5.00 = 5%', max_digits=5)),
            ],
            options={
                'verbose_name': 'Point Transfer Settings',
                'verbose_name_plural': 'Point Transfer Settings',
            },
        ),
        migrations.CreateModel(
            name='PointTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Points transferred')),
                ('fee', models.IntegerField(default=0, help_text='Transfer fee deducted')),
                ('net_amount', models.IntegerField(help_text='Amount received by recipient')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('message', models.CharField(blank=True, help_text='Optional message to recipient', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('was_invite', models.BooleanField(default=False, help_text='Transfer was to invite unregistered user')),
                ('invite_phone', models.CharField(blank=True, help_text='Phone of invited user', max_length=24)),
                ('invite_accepted', models.BooleanField(default=False, help_text='Invited user registered')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_received', to='club.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_sent', to='club.profile')),
            ],
            options={
                'verbose_name': 'Point Transfer',
                'verbose_name_plural': 'Point Transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='Phone number of person being invited', max_length=24)),
                ('points_promised', models.IntegerField(help_text='Points to transfer when they register')),
                ('message', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='club.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('inviter', 'phone')},
            },
        ),
    ]

