# Generated by Django 5.2.4 on 2025-11-09 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_pointtransfersettings_pointtransfer_pendinginvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text="Listing partner's phone number", max_length=24, unique=True)),
                ('company_name', models.CharField(help_text='Company/Brand name', max_length=200)),
                ('code', models.CharField(blank=True, help_text='Unique listing partner code', max_length=8, unique=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('business_registration', models.CharField(blank=True, help_text='Business registration number', max_length=100)),
                ('tax_pin', models.CharField(blank=True, help_text='KRA PIN', max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_account_name', models.CharField(blank=True, max_length=200)),
                ('mpesa_number', models.CharField(blank=True, help_text='M-Pesa paybill/till number', max_length=24)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text="Melvins's commission % on redemptions", max_digits=5)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Total revenue from redemptions', max_digits=12)),
                ('Melvins_commission_earned', models.DecimalField(decimal_places=2, default=0.0, help_text='Total commission earned by Melvins', max_digits=12)),
                ('partner_earnings', models.DecimalField(decimal_places=2, default=0.0, help_text='Net earnings for partner (after commission)', max_digits=12)),
                ('pending_payout', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount pending payout to partner', max_digits=12)),
                ('total_paid_out', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid to partner', max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False, help_text='Approved by Melvins admin')),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='User account for listing partner login', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing Partner',
                'verbose_name_plural': 'Listing Partners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('mpesa', 'M-Pesa'), ('cheque', 'Cheque')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('listing_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='club.listingpartner')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Payout',
                'verbose_name_plural': 'Partner Payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, help_text='e.g., Electronics, Fashion, Food', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_listings/')),
                ('partner_price', models.DecimalField(decimal_places=2, help_text='Price partner wants to receive (KES)', max_digits=10)),
                ('Melvins_price', models.DecimalField(blank=True, decimal_places=2, help_text='Final price set by Melvins (KES)', max_digits=10, null=True)),
                ('points_required', models.IntegerField(blank=True, help_text='Points needed to redeem (set by Melvins)', null=True)),
                ('point_value', models.DecimalField(decimal_places=2, default=1.0, help_text='Value of 1 point in KES (e.g., 1 point = 1 KES)', max_digits=5)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Available stock')),
                ('redemption_limit', models.IntegerField(blank=True, help_text='Max redemptions per user (null = unlimited)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection')),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='Featured product')),
                ('total_redemptions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_products', to=settings.AUTH_USER_MODEL)),
                ('available_at_shops', models.ManyToManyField(blank=True, help_text='Shops where product can be redeemed', limit_choices_to={'partner_type': 'shop'}, related_name='available_products', to='club.partnership')),
                ('listing_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='club.listingpartner')),
            ],
            options={
                'verbose_name': 'Product Listing',
                'verbose_name_plural': 'Product Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_deducted', models.IntegerField(help_text='Points deducted from user')),
                ('amount_charged', models.DecimalField(decimal_places=2, help_text='Amount in KES', max_digits=10)),
                ('Melvins_commission', models.DecimalField(decimal_places=2, help_text='Commission earned by Melvins', max_digits=10)),
                ('partner_earning', models.DecimalField(decimal_places=2, help_text='Amount earned by listing partner', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('redemption_code', models.CharField(blank=True, help_text='Code for verification', max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('paid_to_partner', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='club.productlisting')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_redemptions', to='club.profile')),
                ('redeemed_at_shop', models.ForeignKey(blank=True, limit_choices_to={'partner_type': 'shop'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.partnership')),
            ],
            options={
                'verbose_name': 'Product Redemption',
                'verbose_name_plural': 'Product Redemptions',
                'ordering': ['-created_at'],
            },
        ),
    ]

