# Generated by Django 5.2.4 on 2025-11-10 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_listingpartner_partnerpayout_productlisting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Challenge title', max_length=200)),
                ('description', models.TextField(help_text='Challenge description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='challenges/')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('one_time', 'One-Time Event')], max_length=20)),
                ('start_date', models.DateTimeField(help_text='When challenge starts')),
                ('end_date', models.DateTimeField(help_text='When challenge ends')),
                ('number_of_winners', models.IntegerField(default=1, help_text='How many winners to select')),
                ('reward_type', models.CharField(choices=[('points', 'Points'), ('cash', 'Cash Prize'), ('product', 'Product'), ('voucher', 'Voucher'), ('custom', 'Custom Reward')], default='points', max_length=50)),
                ('reward_value', models.CharField(help_text="e.g., '1000 points' or 'KES 5,000' or 'iPhone 15'", max_length=200)),
                ('reward_description', models.TextField(blank=True, help_text='Additional reward details')),
                ('points_weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight multiplier for points (e.g., 1.0 = normal, 2.0 = double weight)', max_digits=5)),
                ('referrals_weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight multiplier for referrals', max_digits=5)),
                ('min_points_required', models.IntegerField(default=0, help_text='Minimum points to participate')),
                ('min_scans_required', models.IntegerField(default=0, help_text='Minimum scans to participate')),
                ('counties_eligible', models.CharField(blank=True, help_text='Comma-separated counties (leave blank for all)', max_length=500)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('ended', 'Ended'), ('winners_selected', 'Winners Selected')], default='upcoming', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('total_entries', models.IntegerField(default=0, help_text='Total eligible participants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('winners_selected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('points_at_entry', models.IntegerField(help_text="User's points when entered")),
                ('referrals_at_entry', models.IntegerField(help_text="User's referrals when entered")),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='club.challenge')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_entries', to='club.profile')),
            ],
            options={
                'verbose_name': 'Challenge Entry',
                'verbose_name_plural': 'Challenge Entries',
                'ordering': ['-entered_at'],
                'unique_together': {('challenge', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text='Winner position (1st, 2nd, 3rd, etc.)')),
                ('entry_weight', models.DecimalField(decimal_places=2, help_text='Weight used for selection', max_digits=10)),
                ('total_entries', models.IntegerField(help_text='Total participants in challenge')),
                ('prize_claimed', models.BooleanField(default=False)),
                ('prize_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('prize_delivery_notes', models.TextField(blank=True)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='club.challenge')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_wins', to='club.profile')),
            ],
            options={
                'verbose_name': 'Challenge Winner',
                'verbose_name_plural': 'Challenge Winners',
                'ordering': ['challenge', 'position'],
                'unique_together': {('challenge', 'profile')},
            },
        ),
    ]

