# Generated by Django 5.2.4 on 2025-11-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_challenge_challengeentry_challengewinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='draw_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the live draw was completed', null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='draw_in_progress',
            field=models.BooleanField(default=False, help_text='Set to True when live draw is happening'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_public_results',
            field=models.BooleanField(default=False, help_text='If True, anyone can see results. If False, only participants can see winners.'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='live_draw_scheduled',
            field=models.DateTimeField(blank=True, help_text='When the live draw will happen (for social media promotion)', null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='live_draw_url',
            field=models.CharField(blank=True, help_text='YouTube/Facebook Live URL for the draw', max_length=500),
        ),
    ]

