# Generated by Django 5.2.4 on 2025-11-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_challenge_draw_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpartner',
            name='pin',
            field=models.CharField(blank=True, help_text='Hashed PIN for authentication', max_length=128),
        ),
        migrations.AddField(
            model_name='partnership',
            name='pin',
            field=models.CharField(blank=True, help_text='Hashed PIN for authentication', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, help_text='Hashed PIN for authentication', max_length=128),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_public_results',
            field=models.BooleanField(default=False, help_text='If True, anyone can see results'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='live_draw_scheduled',
            field=models.DateTimeField(blank=True, help_text='When the live draw will happen', null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='live_draw_url',
            field=models.CharField(blank=True, help_text='YouTube/Facebook Live URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='points_weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Weight multiplier for points', max_digits=5),
        ),
    ]

