# Generated by Django 5.2.4 on 2025-11-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_listingpartner_pin_partnership_pin_profile_pin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pack Code', 'verbose_name_plural': 'Pack Codes'},
        ),
        migrations.AlterField(
            model_name='packcode',
            name='code',
            field=models.CharField(blank=True, help_text='Unique pack code', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='packcode',
            name='sku',
            field=models.CharField(default='Melvins', max_length=64),
        ),
    ]

