# Generated by Django 6.0.1 on 2026-02-06 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0007_alter_packcode_options_alter_packcode_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstateCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Golden Harvest Collection'", max_length=100
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        help_text="e.g., 'Peak Season Yields'", max_length=100
                    ),
                ),
                ("description", models.TextField()),
                (
                    "start_date",
                    models.DateTimeField(help_text="When collection becomes available"),
                ),
                ("end_date", models.DateTimeField(help_text="Collection deadline")),
                ("is_active", models.BooleanField(default=False)),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="collections/"),
                ),
                (
                    "completion_reward_points",
                    models.IntegerField(
                        default=500, help_text="Points awarded for completing set"
                    ),
                ),
                (
                    "completion_reward_description",
                    models.TextField(blank=True, help_text="Additional reward details"),
                ),
                (
                    "total_cards",
                    models.IntegerField(
                        default=12, help_text="Total cards in this collection"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Estate Collection",
                "verbose_name_plural": "Estate Collections",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TeaEstate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Kericho Valley Estate'", max_length=100
                    ),
                ),
                (
                    "region",
                    models.CharField(help_text="e.g., 'Kericho'", max_length=50),
                ),
                ("description", models.TextField(help_text="Story of this estate")),
                (
                    "elevation",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '2,000m above sea level'",
                        max_length=50,
                    ),
                ),
                (
                    "tasting_notes",
                    models.TextField(
                        blank=True, help_text="Flavor profile of tea from this region"
                    ),
                ),
                (
                    "brewing_tips",
                    models.TextField(
                        blank=True, help_text="Recommended brewing method"
                    ),
                ),
                (
                    "harvest_season",
                    models.CharField(
                        blank=True, help_text="e.g., 'March - May'", max_length=100
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="estates/"),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tea Estate",
                "verbose_name_plural": "Tea Estates",
                "ordering": ["region", "name"],
            },
        ),
        migrations.CreateModel(
            name="EstateCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Estate Pick (Common)"),
                            ("uncommon", "Estate Reserve (Uncommon)"),
                            ("rare", "Grand Reserve (Rare)"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
                (
                    "card_number",
                    models.IntegerField(
                        help_text="Card # in collection (e.g., 1 of 12)"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Card title, defaults to estate name",
                        max_length=100,
                    ),
                ),
                (
                    "flavor_text",
                    models.TextField(
                        blank=True, help_text="Special text for this card"
                    ),
                ),
                (
                    "drop_weight",
                    models.FloatField(
                        default=1.0, help_text="Multiplier for drop probability"
                    ),
                ),
                (
                    "card_image",
                    models.ImageField(blank=True, null=True, upload_to="cards/"),
                ),
                (
                    "frame_color",
                    models.CharField(
                        default="#013328",
                        help_text="Hex color for card frame",
                        max_length=7,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="club.estatecollection",
                    ),
                ),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="club.teaestate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estate Card",
                "verbose_name_plural": "Estate Cards",
                "ordering": ["collection", "card_number"],
                "unique_together": {("collection", "card_number")},
            },
        ),
        migrations.CreateModel(
            name="UserCardCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obtained_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_duplicate",
                    models.BooleanField(
                        default=False, help_text="User already had this card"
                    ),
                ),
                (
                    "is_new",
                    models.BooleanField(
                        default=True, help_text="Card hasn't been viewed yet"
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collectors",
                        to="club.estatecard",
                    ),
                ),
                (
                    "from_pack",
                    models.ForeignKey(
                        blank=True,
                        help_text="The pack code that revealed this card",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="club.packcode",
                    ),
                ),
                (
                    "from_scan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revealed_cards",
                        to="club.scan",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_collection",
                        to="club.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Card Collection",
                "verbose_name_plural": "User Card Collections",
                "ordering": ["-obtained_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("reward_claimed", models.BooleanField(default=False)),
                ("reward_claimed_at", models.DateTimeField(blank=True, null=True)),
                ("points_awarded", models.IntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_collections",
                        to="club.profile",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="club.estatecollection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Completion",
                "verbose_name_plural": "Collection Completions",
                "ordering": ["-completed_at"],
                "unique_together": {("profile", "collection")},
            },
        ),
    ]

