# Generated by Django 6.0.1 on 2026-02-06 07:01

import club.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_estatecollection_teaestate_estatecard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=club.models.generate_token, max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.estatecard')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_gifts', to='club.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_gifts', to='club.profile')),
            ],
            options={
                'verbose_name': 'Card Gift',
                'verbose_name_plural': 'Card Gifts',
            },
        ),
    ]
