# Generated by Django 6.0.2 on 2026-02-07 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_cardgift'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Team name chosen by captain', max_length=100)),
                ('invite_code', models.CharField(blank=True, help_text='Code for friends to join', max_length=6, unique=True)),
                ('max_members', models.IntegerField(default=5, help_text='Maximum team size')),
                ('is_active', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When team completed collection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to='club.profile')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='club.estatecollection')),
            ],
            options={
                'verbose_name': 'Collection Team',
                'verbose_name_plural': 'Collection Teams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamCardCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributed_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_collections', to='club.estatecard')),
                ('contributed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_contributions', to='club.profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_cards', to='club.collectionteam')),
            ],
            options={
                'verbose_name': 'Team Card Collection',
                'verbose_name_plural': 'Team Card Collections',
                'ordering': ['-contributed_at'],
                'unique_together': {('team', 'card')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards_contributed', models.IntegerField(default=0, help_text='Number of cards contributed')),
                ('points_earned', models.IntegerField(default=0, help_text='Points earned from team completion')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='club.profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='club.collectionteam')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['-joined_at'],
                'unique_together': {('team', 'profile')},
            },
        ),
    ]
