# Generated by Django 6.0.2 on 2026-02-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_collectionteam_teamcardcollection_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatecard',
            name='reward_points',
            field=models.IntegerField(default=10, help_text='Points awarded when user obtains this card'),
        ),
    ]
