# Generated by Django 6.0.2 on 2026-02-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_fix_commission_column_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='utm_campaign',
            field=models.CharField(blank=True, help_text='e.g. spring_sale', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='utm_medium',
            field=models.CharField(blank=True, help_text='e.g. cpc, banner, email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='utm_source',
            field=models.CharField(blank=True, help_text='e.g. facebook, twitter, email', max_length=100, null=True),
        ),
    ]
