# Generated by Django 6.0.2 on 2026-02-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_profile_utm_campaign_profile_utm_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productredemption',
            name='Melvins_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission earned by Melvins', max_digits=10),
            preserve_default=False,
        ),
    ]
