# Generated by Django 6.0.2 on 2026-02-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0015_add_commission_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='Melvins_price',
            field=models.DecimalField(decimal_places=2, help_text='Final price set by Melvins (KES)', max_digits=10, null=True, blank=True),
        ),
    ]
